In [57]:
!pip install imblearn

Requirement already satisfied: imblearn in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imblearn) (0.13.0)
Requirement already satisfied: numpy<3,>=1.24.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (2.2.5)
Requirement already satisfied: scipy<2,>=1.10.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.15.2)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: sklearn-compat<1,>=0.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (0.1.3)
Requirement already satisfied: joblib<2,>=1.1.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (1.5.1)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [58]:
import pandas as pd
import statsmodels.api as sm
from imblearn.over_sampling import SMOTE

In [76]:
df = pd.read_csv(r"C:\Users\ASUS\Downloads\df_para_modelo_II.csv")

In [77]:
df

,key_ninos,primary_key,trabajo_infantil,Departamento,Sexo_al_nacer,Edad_en_años_cumplidos,Parentesco_con_el_jefea_del_hogar,¿Madre_reside_en_el_hogar?,¿Padre_reside_en_el_hogar?,¿Alguna_vez_fue_campesinoa?,...,Disponibilidad_de_acueducto,Cantidad_de_hogares_en_la_vivienda,Tipo_de_servicio_sanitario_que_utiliza_el_hogar,Forma_de_disposición_del_servicio_sanitario,Fuente_principal_de_agua_para_consumo_humano,Lugar_donde_se_preparan_los_alimentos,Tipo_de_energía_o_combustible_usado_para_cocinar,Tipo_de_ocupación_de_la_vivienda,Valor_estimado_de_arriendo_si_se_tuviera_que_pagar,Total_de_personas_en_el_hogar
0,730906013,73090601,True,-0.248470,1.021449,-1.116687,-0.499811,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,0.973052,-0.816493,0.000000,-0.907843
1,730906414,73090641,True,1.096032,1.021449,0.492447,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,0.281332
2,730906812,73090681,True,1.096032,1.021449,1.565202,-0.499811,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.355075,-0.058530,-1.502431
3,730906913,73090691,True,1.096032,-0.979001,0.492447,2.150382,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,2.243999,-0.543347,1.490597,-0.101703,0.281332
4,730907013,73090701,True,1.096032,1.021449,1.565202,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,0.281332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176343,756731615,75673161,True,1.544199,1.021449,-1.653064,2.150382,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,1.490597,-0.134062,0.281332
176344,756731814,75673181,True,-0.920721,-0.979001,1.297013,-0.499811,0.398933,-0.795657,-0.078863,...,-2.794228,-0.109813,1.970264,0.142796,0.769199,-0.451025,0.973052,1.490597,-0.026150,1.470508
176345,756731815,75673181,True,-0.920721,1.021449,-0.580309,-0.499811,0.398933,-0.795657,-0.078863,...,-2.794228,-0.109813,1.970264,0.142796,0.769199,-0.451025,0.973052,1.490597,-0.026150,1.470508
176346,756731913,75673191,True,-1.705014,-0.979001,-0.312120,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,-0.907843
176347,756732313,75673231,True,1.544199,-0.979001,-0.580309,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,-0.313255

In [78]:
df['trabajo_infantil'] = df['trabajo_infantil'].replace({False: 0, True: 1})

C:\Users\ASUS\AppData\Local\Temp\ipykernel_19404\1732287144.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['trabajo_infantil'] = df['trabajo_infantil'].replace({False: 0, True: 1})

In [79]:
df

,key_ninos,primary_key,trabajo_infantil,Departamento,Sexo_al_nacer,Edad_en_años_cumplidos,Parentesco_con_el_jefea_del_hogar,¿Madre_reside_en_el_hogar?,¿Padre_reside_en_el_hogar?,¿Alguna_vez_fue_campesinoa?,...,Disponibilidad_de_acueducto,Cantidad_de_hogares_en_la_vivienda,Tipo_de_servicio_sanitario_que_utiliza_el_hogar,Forma_de_disposición_del_servicio_sanitario,Fuente_principal_de_agua_para_consumo_humano,Lugar_donde_se_preparan_los_alimentos,Tipo_de_energía_o_combustible_usado_para_cocinar,Tipo_de_ocupación_de_la_vivienda,Valor_estimado_de_arriendo_si_se_tuviera_que_pagar,Total_de_personas_en_el_hogar
0,730906013,73090601,1,-0.248470,1.021449,-1.116687,-0.499811,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,0.973052,-0.816493,0.000000,-0.907843
1,730906414,73090641,1,1.096032,1.021449,0.492447,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,0.281332
2,730906812,73090681,1,1.096032,1.021449,1.565202,-0.499811,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.355075,-0.058530,-1.502431
3,730906913,73090691,1,1.096032,-0.979001,0.492447,2.150382,0.398933,-0.795657,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,2.243999,-0.543347,1.490597,-0.101703,0.281332
4,730907013,73090701,1,1.096032,1.021449,1.565202,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,0.761634,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,0.281332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176343,756731615,75673161,1,1.544199,1.021449,-1.653064,2.150382,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,1.490597,-0.134062,0.281332
176344,756731814,75673181,1,-0.920721,-0.979001,1.297013,-0.499811,0.398933,-0.795657,-0.078863,...,-2.794228,-0.109813,1.970264,0.142796,0.769199,-0.451025,0.973052,1.490597,-0.026150,1.470508
176345,756731815,75673181,1,-0.920721,1.021449,-0.580309,-0.499811,0.398933,-0.795657,-0.078863,...,-2.794228,-0.109813,1.970264,0.142796,0.769199,-0.451025,0.973052,1.490597,-0.026150,1.470508
176346,756731913,75673191,1,-1.705014,-0.979001,-0.312120,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,-0.907843
176347,756732313,75673231,1,1.544199,-0.979001,-0.580309,-0.499811,0.398933,1.006294,-0.078863,...,0.357881,-0.109813,-0.446996,0.142796,0.006170,-0.451025,-0.543347,-0.816493,0.000000,-0.313255

In [80]:
from sklearn.model_selection import train_test_split

# Dividir el conjunto de datos en entrenamiento y prueba
train, test = train_test_split(df, test_size=0.3, random_state=42)

# Dividir el conjunto de prueba en prueba y validación
test, validation = train_test_split(test, test_size=0.5, random_state=42)

# Verificar las dimensiones de cada conjunto
print(f"Entrenamiento: {train.shape}")
print(f"Prueba: {test.shape}")
print(f"Validación: {validation.shape}")

Entrenamiento: (123443, 58)
Prueba: (26452, 58)
Validación: (26453, 58)

In [85]:
validation_2 = validation.copy()

In [86]:
# Eliminar las columnas 'key_ninos' y 'primary_key' de todas las particiones
train = train.drop(columns=['key_ninos', 'primary_key'])
test = test.drop(columns=['key_ninos', 'primary_key'])
validation = validation.drop(columns=['key_ninos', 'primary_key'])

In [88]:
# Separar las características (X) y la variable objetivo (y) del conjunto de entrenamiento
X_train = train.drop(columns=['trabajo_infantil'])
y_train = train['trabajo_infantil']

In [89]:
# Aplicar SMOTE para balancear las clases
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificar la distribución de clases después del balanceo
print("Distribución de clases antes del balanceo:")
print(y_train.value_counts())
print("\nDistribución de clases después del balanceo:")
print(y_train_balanced.value_counts())

Distribución de clases antes del balanceo:
trabajo_infantil
1    111364
0     12079
Name: count, dtype: int64

Distribución de clases después del balanceo:
trabajo_infantil
1    111364
0    111364
Name: count, dtype: int64

In [90]:
# Agregar constante para el intercepto
X_train_balanced_with_const = sm.add_constant(X_train_balanced)

# Ajustar el modelo logístico con statsmodels
logit_model = sm.Logit(y_train_balanced, X_train_balanced_with_const).fit()

# Mostrar el resumen con coeficientes, errores estándar, z, p-valores, etc.
print(logit_model.summary())

Optimization terminated successfully.
         Current function value: 0.117324
         Iterations 16
                           Logit Regression Results
==============================================================================
Dep. Variable:       trabajo_infantil   No. Observations:               222728
Model:                          Logit   Df Residuals:                   222673
Method:                           MLE   Df Model:                           54
Date:                Sun, 08 Jun 2025   Pseudo R-squ.:                  0.8307
Time:                        19:38:22   Log-Likelihood:                -26131.
converged:                       True   LL-Null:                   -1.5438e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==========================================================================================================================
                                                             coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------------
const                                                     40.0268      0.654     61.158      0.000      38.744      41.310
Departamento                                               0.2528      0.013     19.857      0.000       0.228       0.278
Sexo_al_nacer                                             -0.0169      0.012     -1.389      0.165      -0.041       0.007
Edad_en_años_cumplidos                                     0.0769      0.028      2.769      0.006       0.022       0.131
Parentesco_con_el_jefea_del_hogar                          0.0193      0.015      1.323      0.186      -0.009       0.048
¿Madre_reside_en_el_hogar?                                 0.0716      0.015      4.725      0.000       0.042       0.101
¿Padre_reside_en_el_hogar?                                 0.0934      0.013      6.962      0.000       0.067       0.120
¿Alguna_vez_fue_campesinoa?                               -0.0322      0.012     -2.622      0.009      -0.056      -0.008
Autoidentificación_étnica                                  0.3735      0.021     17.851      0.000       0.332       0.415
Estado_civil                                               0.0300      0.015      2.020      0.043       0.001       0.059
¿Cónyuge_reside_en_el_hogar?                              -0.0349      0.020     -1.777      0.076      -0.073       0.004
COVID:_estuvo_enfermoa                                     0.0125      0.012      1.041      0.298      -0.011       0.036
COVID:_dificultad_con_alimentos/productos                 -0.0262      0.018     -1.496      0.135      -0.061       0.008
COVID:_dificultad_con_pagos/deudas                         0.0146      0.015      0.972      0.331      -0.015       0.044
COVID:_reducción_de_ingresos                              -0.0499      0.015     -3.409      0.001      -0.079      -0.021
COVID:_sin_trabajo_o_sin_poder_buscarlo                   -0.0845      0.050     -1.680      0.093      -0.183       0.014
COVID:_suspensión_contrato_sin_paga                       -0.0002      0.013     -0.012      0.990      -0.025       0.024
COVID:_pérdida_de_trabajo_o_ingresos                      -0.0309      0.016     -1.946      0.052      -0.062       0.000
COVID:_suspensión_de_clases                                0.0012      0.021      0.057      0.955      -0.040       0.043
COVID:_malestar_emocional                                 -0.0282      0.013     -2.206      0.027      -0.053      -0.003
COVID:_otra_dificultad                                    -0.0166      0.016     -1.031      0.303      -0.048       0.015
COVID:_sin_dificultades                                    0.0001      0.020      0.006      0.995      -0.039       0.039
Afiliación_sistema_de_salud                                0.0002      0.012      0.020      0.984      -0.023       0.024
Régimen_de_salud                                           0.0512      0.012      4.210      0.000       0.027       0.075
Dificultad_auditiva                                        0.0599      0.017      3.578      0.000       0.027       0.093
Dificultad_para_hablar                                     0.1208      0.028      4.342      0.000       0.066       0.175
Dificultad_visual                                          0.0389      0.014      2.850      0.004       0.012       0.066
Dificultad_motriz                                          0.0005      0.017      0.032      0.975      -0.033       0.034
Dificultad_en_manos                                       -0.0317   1.14e+06  -2.78e-08      1.000   -2.23e+06    2.23e+06
Dificultad_cognitiva                                      -0.0317   1.14e+06  -2.78e-08      1.000   -2.23e+06    2.23e+06
Dificultad_en_autocuidado                                  0.1702      0.034      5.021      0.000       0.104       0.237
Dificultad_para_relacionarse                               0.1622      0.030      5.319      0.000       0.102       0.222
¿Sabe_leer_y_escribir?                                     0.0094      0.015      0.625      0.532      -0.020       0.039
¿Asiste_actualmente_a_clase?                               0.0331      0.014      2.294      0.022       0.005       0.061
Tipo_de_institución_educativa                             -0.0157      0.011     -1.385      0.166      -0.038       0.007
Nivel_educativo_y_grado_aprobado                          -0.1115      0.018     -6.276      0.000      -0.146      -0.077
Condición_de_discapacidad                                 -0.3043      0.025    -12.234      0.000      -0.353      -0.256
Pertenencia_a_comunidad_campesina                         -0.3727      0.012    -29.902      0.000      -0.397      -0.348
Tipo_de_vivienda                                          -6.7100      0.095    -70.916      0.000      -6.895      -6.525
Material_predominante_de_las_paredes_exteriores           -0.2463      0.087     -2.836      0.005      -0.416      -0.076
Material_predominante_del_piso                             6.8026      0.165     41.175      0.000       6.479       7.126
Disponibilidad_de_energía_eléctrica                       13.8224      0.209     66.214      0.000      13.413      14.232
Estrato_para_tarifa_de_electricidad                        0.0185      0.012      1.541      0.123      -0.005       0.042
Disponibilidad_de_gas_natural_por_red_pública            -12.7845      0.499    -25.595      0.000     -13.763     -11.806
Disponibilidad_de_alcantarillado                          -3.9576      0.210    -18.829      0.000      -4.370      -3.546
Frecuencia_de_recolección_de_basura_(veces_por_semana)    -1.5266      0.028    -53.684      0.000      -1.582      -1.471
Disponibilidad_de_acueducto                               -2.4583      0.239    -10.295      0.000      -2.926      -1.990
Cantidad_de_hogares_en_la_vivienda                         6.3482      1.210      5.246      0.000       3.976       8.720
Tipo_de_servicio_sanitario_que_utiliza_el_hogar           -2.0896      0.188    -11.101      0.000      -2.459      -1.721
Forma_de_disposición_del_servicio_sanitario               -4.9401      0.172    -28.745      0.000      -5.277      -4.603
Fuente_principal_de_agua_para_consumo_humano              -1.7929      0.079    -22.619      0.000      -1.948      -1.638
Lugar_donde_se_preparan_los_alimentos                      4.5709      0.204     22.459      0.000       4.172       4.970
Tipo_de_energía_o_combustible_usado_para_cocinar           1.8832      0.184     10.223      0.000       1.522       2.244
Tipo_de_ocupación_de_la_vivienda                          24.9503      0.574     43.496      0.000      23.826      26.075
Valor_estimado_de_arriendo_si_se_tuviera_que_pagar         8.1424      4.044      2.013      0.044       0.215      16.069
Total_de_personas_en_el_hogar                             -2.1656      0.030    -71.613      0.000      -2.225      -2.106
==========================================================================================================================

Possibly complete quasi-separation: A fraction 0.47 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [91]:
# Add a constant to the validation data for the intercept
X_validation_with_const = sm.add_constant(validation.drop(columns=['trabajo_infantil']))

# Make predictions using the logistic regression model
y_validation_pred_logit = logit_model.predict(X_validation_with_const)

# Display the predictions
print(y_validation_pred_logit)

112628    1.000000
72850     0.999994
108786    1.000000
101175    0.999112
18191     0.797601
            ...
82202     1.000000
146392    1.000000
70054     0.050794
33553     1.000000
132866    0.999999
Length: 26453, dtype: float64

In [101]:
prediccion = y_validation_pred_logit.to_frame(name='prediccion')

In [105]:
validation_2['prediccion'] = prediccion['prediccion'].values

In [106]:
validation_2

,key_ninos,primary_key,trabajo_infantil,Departamento,Sexo_al_nacer,Edad_en_años_cumplidos,Parentesco_con_el_jefea_del_hogar,¿Madre_reside_en_el_hogar?,¿Padre_reside_en_el_hogar?,¿Alguna_vez_fue_campesinoa?,...,Cantidad_de_hogares_en_la_vivienda,Tipo_de_servicio_sanitario_que_utiliza_el_hogar,Forma_de_disposición_del_servicio_sanitario,Fuente_principal_de_agua_para_consumo_humano,Lugar_donde_se_preparan_los_alimentos,Tipo_de_energía_o_combustible_usado_para_cocinar,Tipo_de_ocupación_de_la_vivienda,Valor_estimado_de_arriendo_si_se_tuviera_que_pagar,Total_de_personas_en_el_hogar,prediccion
112628,744435013,74443501,1,-1.032763,-0.979001,-0.848498,-0.499811,0.398933,-0.795657,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,2.243999,-0.543347,-0.816493,0.000000,0.875920,1.000000
72850,736739912,73673991,1,-1.705014,1.021449,-0.848498,-0.499811,0.398933,-0.795657,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,-0.907843,0.999994
108786,743684214,74368421,1,-1.144805,-0.979001,0.760635,-0.499811,0.398933,1.006294,-0.078863,...,-0.109813,0.761634,0.142796,0.00617,1.345658,2.489451,1.490597,-0.123290,-0.313255,1.000000
101175,742180812,74218081,1,-0.472554,1.021449,1.565202,-0.499811,0.398933,-0.795657,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,-0.907843,0.999112
18191,757407312,75740731,1,-0.920721,-0.979001,1.565202,-1.088743,-2.208305,-0.795657,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,-0.907843,0.797601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82202,738515112,73851511,1,0.423781,-0.979001,1.297013,-0.499811,0.398933,-0.795657,-0.078863,...,-0.109813,0.761634,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,-1.502431,1.000000
146392,750842113,75084211,1,0.311739,-0.979001,1.297013,-0.499811,0.398933,1.006294,-0.078863,...,-0.109813,0.761634,0.142796,0.00617,3.142341,0.973052,0.567761,-0.101703,0.875920,1.000000
70054,736231115,73623111,0,1.544199,1.021449,-1.384875,-0.499811,0.398933,-0.795657,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,0.281332,0.050794
33553,760566013,76056601,1,-0.920721,-0.979001,-1.653064,-0.499811,0.398933,1.006294,-0.078863,...,-0.109813,-0.446996,0.142796,0.00617,-0.451025,-0.543347,-0.355075,0.038610,-0.907843,1.000000
132866,748272517,74827251,1,0.311739,-0.979001,0.224258,2.150382,0.398933,-0.795657,-0.078863,...,-0.109813,0.761634,0.142796,0.00617,-0.451025,-0.543347,-0.816493,0.000000,2.659684,0.999999

In [107]:
validation_2 = validation_2[['key_ninos', 'primary_key', 'prediccion']]

In [108]:
df = pd.read_parquet(r'C:\Users\ASUS\Downloads\finallabeled_.parquet')

In [109]:
# Realizar el merge entre validation_2 y df utilizando la columna key_ninos
merged_df = pd.merge(validation_2, df, on='key_ninos', how='inner')

# Mostrar las primeras filas del DataFrame resultante
print(merged_df.head())

   key_ninos  primary_key_x  prediccion  primary_key_y Departamento  \
0  744435013       74443501    1.000000       74443501       Boyacá
1  736739912       73673991    0.999994       73673991    Antioquia
2  743684214       74368421    1.000000       74368421      Bolívar
3  742180812       74218081    0.999112       74218081        Cesar
4  757407312       75740731    0.797601       75740731       Caldas

  Sexo al nacer  Edad en años cumplidos  \
0        Hombre                       8
1         Mujer                       8
2        Hombre                      14
3         Mujer                      17
4        Hombre                      17

                 Parentesco con el jefe(a) del hogar  \
0                               Hijo(a), hijastro(a)
1                               Hijo(a), hijastro(a)
2                               Hijo(a), hijastro(a)
3                               Hijo(a), hijastro(a)
4  Empleado(a) del servicio doméstico y sus parie...

  ¿Madre reside en el hogar? ¿Padre reside en el hogar?  ...  \
0                         Sí                         No  ...
1                         Sí                         No  ...
2                         Sí                         Sí  ...
3                         Sí                         No  ...
4                         No                         No  ...

  Tipo de servicio sanitario que utiliza el hogar  \
0              Inodoro conectado a alcantarillado
1              Inodoro conectado a alcantarillado
2                Inodoro conectado a pozo séptico
3              Inodoro conectado a alcantarillado
4              Inodoro conectado a alcantarillado

  Forma de disposición del servicio sanitario  \
0  De uso exclusivo de las personas del hogar
1  De uso exclusivo de las personas del hogar
2  De uso exclusivo de las personas del hogar
3  De uso exclusivo de las personas del hogar
4  De uso exclusivo de las personas del hogar

  Método de eliminación de basuras en el hogar  \
0            Por recolección pública o privada
1            Por recolección pública o privada
2            Por recolección pública o privada
3            Por recolección pública o privada
4            Por recolección pública o privada

  Fuente principal de agua para consumo humano  \
0                     De acueducto por tubería
1                     De acueducto por tubería
2                     De acueducto por tubería
3                     De acueducto por tubería
4                     De acueducto por tubería

            Lugar donde se preparan los alimentos  \
0              En una sala comedor con lavaplatos
1            En un cuarto usado solo para cocinar
2  En un patio, corredor, enramada, al aire libre
3            En un cuarto usado solo para cocinar
4            En un cuarto usado solo para cocinar

  Tipo de energía o combustible usado para cocinar  \
0              Gas natural conectado a red pública
1              Gas natural conectado a red pública
2                    Leña, madera o carbón de leña
3              Gas natural conectado a red pública
4              Gas natural conectado a red pública

  Tipo de ocupación de la vivienda  \
0        En arriendo o subarriendo
1        En arriendo o subarriendo
2        Propia, totalmente pagada
3        En arriendo o subarriendo
4        En arriendo o subarriendo

  Valor estimado de arriendo si se tuviera que pagar  \
0                                      621140.830428
1                                      621140.830428
2                                       50000.000000
3                                      621140.830428
4                                      621140.830428

  Total de personas en el hogar trabajo_infantil
0                           6.0             True
1                           3.0             True
2                           4.0             True
3                           3.0             True
4                           3.0             True

[5 rows x 66 columns]

Este es el df final para validación con la predicción

In [114]:
merged_df.to_csv(r'C:\Users\ASUS\Downloads\df_resultado.csv', index=False)

In [52]:
from sklearn.metrics import f1_score

# Convert predictions to binary using a threshold of 0.5
y_validation_pred_logit_binary = (y_validation_pred_logit >= 0.5).astype(int)

# Calculate the F1 score
f1_score_logit = f1_score(validation['trabajo_infantil'], y_validation_pred_logit_binary)
print("F1 score for the logistic model:", f1_score_logit)

F1 score for the logistic model: 0.9712436630352713

In [53]:
# Combine X_validation_with_const and y_validation_pred_logit into a single DataFrame
validation_with_predictions = X_validation_with_const.copy()
validation_with_predictions['Prediction'] = y_validation_pred_logit

# Display the resulting DataFrame
print(validation_with_predictions.head())

        const  Departamento  Sexo_al_nacer  Edad_en_años_cumplidos  \
112628    1.0     -1.032763      -0.979001               -0.848498
72850     1.0     -1.705014       1.021449               -0.848498
108786    1.0     -1.144805      -0.979001                0.760635
101175    1.0     -0.472554       1.021449                1.565202
18191     1.0     -0.920721      -0.979001                1.565202

        Parentesco_con_el_jefea_del_hogar  ¿Madre_reside_en_el_hogar?  \
112628                          -0.499811                    0.398933
72850                           -0.499811                    0.398933
108786                          -0.499811                    0.398933
101175                          -0.499811                    0.398933
18191                           -1.088743                   -2.208305

        ¿Padre_reside_en_el_hogar?  ¿Alguna_vez_fue_campesinoa?  \
112628                   -0.795657                    -0.078863
72850                    -0.795657                    -0.078863
108786                    1.006294                    -0.078863
101175                   -0.795657                    -0.078863
18191                    -0.795657                    -0.078863

        Autoidentificación_étnica  Estado_civil  ...  \
112628                   0.379189      -0.08026  ...
72850                    0.379189      -0.08026  ...
108786                   0.379189      -0.08026  ...
101175                   0.379189      -0.08026  ...
18191                    0.379189      -0.08026  ...

        Cantidad_de_hogares_en_la_vivienda  \
112628                           -0.109813
72850                            -0.109813
108786                           -0.109813
101175                           -0.109813
18191                            -0.109813

        Tipo_de_servicio_sanitario_que_utiliza_el_hogar  \
112628                                        -0.446996
72850                                         -0.446996
108786                                         0.761634
101175                                        -0.446996
18191                                         -0.446996

        Forma_de_disposición_del_servicio_sanitario  \
112628                                     0.142796
72850                                      0.142796
108786                                     0.142796
101175                                     0.142796
18191                                      0.142796

        Fuente_principal_de_agua_para_consumo_humano  \
112628                                       0.00617
72850                                        0.00617
108786                                       0.00617
101175                                       0.00617
18191                                        0.00617

        Lugar_donde_se_preparan_los_alimentos  \
112628                               2.243999
72850                               -0.451025
108786                               1.345658
101175                              -0.451025
18191                               -0.451025

        Tipo_de_energía_o_combustible_usado_para_cocinar  \
112628                                         -0.543347
72850                                          -0.543347
108786                                          2.489451
101175                                         -0.543347
18191                                          -0.543347

        Tipo_de_ocupación_de_la_vivienda  \
112628                         -0.816493
72850                          -0.816493
108786                          1.490597
101175                         -0.816493
18191                          -0.816493

        Valor_estimado_de_arriendo_si_se_tuviera_que_pagar  \
112628                                            0.00000
72850                                             0.00000
108786                                           -0.12329
101175                                            0.00000
18191                                             0.00000

        Total_de_personas_en_el_hogar  Prediction
112628                       0.875920    1.000000
72850                       -0.907843    0.999994
108786                      -0.313255    1.000000
101175                      -0.907843    0.999112
18191                       -0.907843    0.797601

[5 rows x 57 columns]

In [18]:
from sklearn.metrics import f1_score

# Convertir las predicciones a valores binarios (0 o 1) usando un umbral de 0.5
y_validation_pred_logit_binary = (y_validation_pred_logit >= 0.5).astype(int)

# Calcular el F1 score
f1_score_logit = f1_score(validation['trabajo_infantil'], y_validation_pred_logit_binary)
print("F1 score para el modelo logístico:", f1_score_logit)

F1 score para el modelo logístico: 0.9916264907383913

In [19]:
from sklearn.metrics import precision_score, accuracy_score

# Calcular precisión
precision_logit = precision_score(validation['trabajo_infantil'], y_validation_pred_logit_binary)
print("Precisión (Precision) para el modelo logístico:", precision_logit)

# Calcular exactitud
accuracy_logit = accuracy_score(validation['trabajo_infantil'], y_validation_pred_logit_binary)
print("Exactitud (Accuracy) para el modelo logístico:", accuracy_logit)

Precisión (Precision) para el modelo logístico: 0.9998720736855571
Exactitud (Accuracy) para el modelo logístico: 0.9850300533020829

In [20]:
from sklearn.metrics import recall_score

# Calcular el recall
recall_logit = recall_score(validation['trabajo_infantil'], y_validation_pred_logit_binary)
print("Recall para el modelo logístico:", recall_logit)

Recall para el modelo logístico: 0.9835157921228136

In [21]:
from sklearn.metrics import f1_score

In [ ]:
# Mostrar los mejores hiperparámetros y el mejor puntaje F1
print("Mejor F1 score:", grid_search.best_score_)

# Evaluar el modelo en el conjunto de validación
best_model = grid_search.best_estimator_
y_validation = validation['trabajo_infantil']  # <-- Línea agregada
y_validation_pred = best_model.predict(validation.drop(columns=['trabajo_infantil']))
validation_f1_score = f1_score(y_validation, y_validation_pred)
print("F1 score en el conjunto de validación:", validation_f1_score)

Mejores hiperparámetros: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
Mejor F1 score: 0.9967632423878106
F1 score en el conjunto de validación: 0.9915838443645592

In [32]:
!pip install --upgrade pip setuptools wheel

Requirement already satisfied: pip in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (25.0.1)
Collecting pip
  Using cached pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: setuptools in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (79.0.0)
Collecting setuptools
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Using cached pip-25.1.1-py3-none-any.whl (1.8 MB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)

WARNING: Ignoring invalid distribution ~ip (C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: To modify pip, please run the following command:
C:\Users\ASUS\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip setuptools wheel

In [10]:
from sklearn.model_selection import cross_val_score

# Realizar validación cruzada con el modelo y los datos balanceados
cv_scores = cross_val_score(
    estimator=logistic_model,
    X=X_train_balanced,
    y=y_train_balanced,
    scoring=make_scorer(f1_score),
    cv=5  # Número de folds
)

# Mostrar los resultados de la validación cruzada
print("Puntajes F1 en cada fold:", cv_scores)
print("Puntaje F1 promedio:", cv_scores.mean())

Puntajes F1 en cada fold: [0.99242304 0.99144254 0.99171571 0.99141893 0.99182944]
Puntaje F1 promedio: 0.9917659327195038