In [6]:
import pandas as pd
import os

In [7]:
df_caracteristicas = pd.read_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/caracteristicas.csv", sep=";", encoding="latin1")
df_caracteristicas.head()

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P3039,POB_MAY18,LGB_Numerica,LGB_sectores,LGBT_Numerica,Trans_numerica,Discapacidad,Dificultad,Campesina,folder_id
0,20230104,1,2023,7309060,1,1,1,10,NaN,1,...,2.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1
1,20230104,1,2023,7309060,1,2,1,10,NaN,1,...,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1
2,20230104,1,2023,7309060,1,3,1,10,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1
3,20230104,1,2023,7309061,1,1,1,10,NaN,1,...,2.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1
4,20230104,1,2023,7309061,1,2,1,10,NaN,1,...,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1

In [8]:
df_caracteristicas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860802 entries, 0 to 860801
Data columns (total 75 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PERIODO         860802 non-null  int64
 1   MES             860802 non-null  int64
 2   PER             860802 non-null  int64
 3   DIRECTORIO      860802 non-null  int64
 4   SECUENCIA_P     860802 non-null  int64
 5   ORDEN           860802 non-null  int64
 6   HOGAR           860802 non-null  int64
 7   REGIS           860802 non-null  int64
 8   AREA            620358 non-null  float64
 9   CLASE           860802 non-null  int64
 10  FEX_C18         860802 non-null  float64
 11  DPTO            860802 non-null  int64
 12  PT              860802 non-null  int64
 13  P6016           860802 non-null  int64
 14  P3271           860802 non-null  int64
 15  P6040           860802 non-null  int64
 16  P6030S1         853405 non-null  float64
 17  P6030S3         853405 non-null  float64
 18  P6050           860802 non-null  int64
 19  P6083           860802 non-null  int64
 20  P6083S1         336896 non-null  float64
 21  P6081           860802 non-null  int64
 22  P6081S1         180688 non-null  float64
 23  P2057           860802 non-null  int64
 24  P2059           608795 non-null  float64
 25  P2061           860802 non-null  int64
 26  P6080           860802 non-null  int64
 27  P6080S1         35883 non-null   object
 28  P6080S1A1       0 non-null       float64
 29  P6070           743034 non-null  float64
 30  P6071           328247 non-null  float64
 31  P6071S1         310797 non-null  float64
 32  P3147S1         165236 non-null  float64
 33  P3147S2         150930 non-null  float64
 34  P3147S3         103604 non-null  float64
 35  P3147S4         203448 non-null  float64
 36  P3147S5         20847 non-null   float64
 37  P3147S6         11245 non-null   float64
 38  P3147S7         62925 non-null   float64
 39  P3147S8         102457 non-null  float64
 40  P3147S9         129522 non-null  float64
 41  P3147S10        2205 non-null    float64
 42  P3147S11        264365 non-null  float64
 43  P3147S10A1      2205 non-null    object
 44  P6090           860802 non-null  int64
 45  P6100           821462 non-null  float64
 46  P6110           370204 non-null  float64
 47  P6120           207153 non-null  float64
 48  P1906S1         860802 non-null  int64
 49  P1906S2         860802 non-null  int64
 50  P1906S3         860802 non-null  int64
 51  P1906S4         860802 non-null  int64
 52  P1906S5         860802 non-null  int64
 53  P1906S6         860802 non-null  int64
 54  P1906S7         860802 non-null  int64
 55  P1906S8         860802 non-null  int64
 56  P6160           831109 non-null  float64
 57  P6170           831109 non-null  float64
 58  P3041           226147 non-null  float64
 59  P3042           831109 non-null  float64
 60  P3042S1         831109 non-null  float64
 61  P3042S2         204772 non-null  float64
 62  P3043           421616 non-null  float64
 63  P3043S1         157682 non-null  float64
 64  P3038           631485 non-null  float64
 65  P3039           631485 non-null  float64
 66  POB_MAY18       631485 non-null  float64
 67  LGB_Numerica    108056 non-null  float64
 68  LGB_sectores    1049 non-null    float64
 69  LGBT_Numerica   108056 non-null  float64
 70  Trans_numerica  108056 non-null  float64
 71  Discapacidad    138317 non-null  float64
 72  Dificultad      138317 non-null  float64
 73  Campesina       147685 non-null  float64
 74  folder_id       860802 non-null  int64
dtypes: float64(43), int64(30), object(2)
memory usage: 492.6+ MB

In [11]:
df_caracteristicas['primary_key'] = df_caracteristicas['DIRECTORIO'].astype(str) + '' + df_caracteristicas['SECUENCIA_P'].astype(str)
df_caracteristicas = df_caracteristicas[['primary_key'] + [col for col in df_caracteristicas.columns if col != 'primary_key']]
df_caracteristicas.head()

,primary_key,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P3039,POB_MAY18,LGB_Numerica,LGB_sectores,LGBT_Numerica,Trans_numerica,Discapacidad,Dificultad,Campesina,folder_id
0,73090601,20230104,1,2023,7309060,1,1,1,10,NaN,...,2.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1
1,73090601,20230104,1,2023,7309060,1,2,1,10,NaN,...,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1
2,73090601,20230104,1,2023,7309060,1,3,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1
3,73090611,20230104,1,2023,7309061,1,1,1,10,NaN,...,2.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1
4,73090611,20230104,1,2023,7309061,1,2,1,10,NaN,...,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1

In [12]:
# Guardar CSV final
df_caracteristicas.to_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/key_caracteristicas.csv", sep=";", index=False, encoding="latin1")
print(f"✅ Archivo guardado con {len(df_caracteristicas)} filas y columnas en orden estándar.")

✅ Archivo guardado con 860802 filas y columnas en orden estándar.

In [5]:
df_hogar = pd.read_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/datos_hogar.csv", sep=";", encoding="latin1")
df_hogar.head()

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,...,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S9,P5222S10,P5222S8A1,P6008,folder_id
0,20230104,1,2023,7309060,1,1,1,NaN,1,1580.677273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1
1,20230104,1,2023,7309061,1,1,1,NaN,1,1001.660782,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
2,20230104,1,2023,7309062,1,1,1,NaN,1,1276.331637,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1,1
3,20230104,1,2023,7309063,1,1,1,NaN,1,1276.331637,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1,1
4,20230104,1,2023,7309064,1,1,1,NaN,2,324.598262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1

In [7]:
df_hogar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268501 entries, 0 to 268500
Data columns (total 49 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   PERIODO      268501 non-null  int64
 1   MES          268501 non-null  int64
 2   PER          268501 non-null  int64
 3   DIRECTORIO   268501 non-null  int64
 4   SECUENCIA_P  268501 non-null  int64
 5   HOGAR        268501 non-null  int64
 6   REGIS        268501 non-null  int64
 7   AREA         193668 non-null  float64
 8   CLASE        268501 non-null  int64
 9   FEX_C18      268501 non-null  float64
 10  DPTO         268501 non-null  int64
 11  P4000        268501 non-null  int64
 12  P4010        268501 non-null  int64
 13  P4020        268501 non-null  int64
 14  P4030S1      268501 non-null  int64
 15  P4030S1A1    266431 non-null  float64
 16  P4030S2      268501 non-null  int64
 17  P4030S3      268501 non-null  int64
 18  P4030S4      268501 non-null  int64
 19  P4030S4A1    243450 non-null  float64
 20  P4030S5      268501 non-null  int64
 21  P70          268501 non-null  int64
 22  P5000        268501 non-null  int64
 23  P5010        268501 non-null  int64
 24  P5020        268501 non-null  int64
 25  P5030        263577 non-null  float64
 26  P5040        268501 non-null  int64
 27  P5050        268501 non-null  int64
 28  P5070        268501 non-null  int64
 29  P5080        264130 non-null  float64
 30  P5090        268501 non-null  int64
 31  P5090S1      1401 non-null    object
 32  P5100        9793 non-null    float64
 33  P5110        92592 non-null   float64
 34  P5130        159064 non-null  float64
 35  P5140        109437 non-null  float64
 36  P5222S1      3528 non-null    float64
 37  P5222S2      168146 non-null  float64
 38  P5222S3      1490 non-null    float64
 39  P5222S4      7379 non-null    float64
 40  P5222S5      2286 non-null    float64
 41  P5222S6      15743 non-null   float64
 42  P5222S7      25495 non-null   float64
 43  P5222S8      4464 non-null    float64
 44  P5222S9      93543 non-null   float64
 45  P5222S10     379 non-null     float64
 46  P5222S8A1    4464 non-null    object
 47  P6008        268501 non-null  int64
 48  folder_id    268501 non-null  int64
dtypes: float64(20), int64(27), object(2)
memory usage: 100.4+ MB

In [8]:
df_hogar['primary_key'] = df_hogar['DIRECTORIO'].astype(str) + '' + df_hogar['SECUENCIA_P'].astype(str)
df_hogar = df_hogar[['primary_key'] + [col for col in df_hogar.columns if col != 'primary_key']]
df_hogar.head()

,primary_key,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,...,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S9,P5222S10,P5222S8A1,P6008,folder_id
0,73090601,20230104,1,2023,7309060,1,1,1,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1
1,73090611,20230104,1,2023,7309061,1,1,1,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
2,73090621,20230104,1,2023,7309062,1,1,1,NaN,1,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1,1
3,73090631,20230104,1,2023,7309063,1,1,1,NaN,1,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1,1
4,73090641,20230104,1,2023,7309064,1,1,1,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1

In [10]:
# Guardar CSV final
df_hogar.to_csv("C:/Users/Santiago/OneDrive - Universidad EAFIT/Documents/EAFIT/CAOBA/PROYECTO_INTEGRADOR_2025II/DATA/PROCESSED/key_hogar.csv", sep=";", index=False, encoding="latin1")
print(f"✅ Archivo guardado con {len(df_hogar)} filas y columnas en orden estándar.")

✅ Archivo guardado con 268501 filas y columnas en orden estándar.